name: e_commerce_app
description: "A new Flutter project."
publish_to: "none" 


environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.2.1
  http: ^1.4.0
  flutter_launcher_icons: ^0.14.3
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  go_router: ^15.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Branding.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/Branding.png"
    background_color: "#E8F0F2"
    theme_color: "#D4AF37"
  windows:
    generate: true
    image_path: "assets/images/Branding.png"
    icon_size: 48

